spring:
  application:
    name: dairy

  datasource:
    url: jdbc:postgresql://localhost:5432/dairy
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false

  thymeleaf:
    cache: false

server:
  port: 8080